version: "2"

services:
  skola24asical.se:
    build: .
    container_name: skola24asical.se
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - VIRTUAL_HOST=skola24.robingronberg.se
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=skola24.robingronberg..se
      - LETSENCRYPT_EMAIL=robingronberg@gmail.com
      - VIRTUAL_NETWORK=nginx-proxy
    entrypoint: node app.js
    networks:
      - proxy-tier